<a href="https://colab.research.google.com/github/KristineYW/DS-Unit-2-Kaggle-Challenge/blob/master/Kristine_Wang_LS_DS_223_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 2, Sprint 2, Module 3*

---

# Cross-Validation


## Assignment
- [ ] [Review requirements for your portfolio project](https://lambdaschool.github.io/ds/unit2), then submit your dataset.
- [ ] Continue to participate in our Kaggle challenge. 
- [ ] Use scikit-learn for hyperparameter optimization with RandomizedSearchCV.
- [ ] Submit your predictions to our Kaggle competition. (Go to our Kaggle InClass competition webpage. Use the blue **Submit Predictions** button to upload your CSV file. Or you can use the Kaggle API to submit your predictions.)
- [ ] Commit your notebook to your fork of the GitHub repo.


**You can't just copy** from the lesson notebook to this assignment.

- Because the lesson was **regression**, but the assignment is **classification.**
- Because the lesson used [TargetEncoder](https://contrib.scikit-learn.org/categorical-encoding/targetencoder.html), which doesn't work as-is for _multi-class_ classification.

So you will have to adapt the example, which is good real-world practice.

1. Use a model for classification, such as [RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)
2. Use hyperparameters that match the classifier, such as `randomforestclassifier__ ...`
3. Use a metric for classification, such as [`scoring='accuracy'`](https://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values)
4. If you’re doing a multi-class classification problem — such as whether a waterpump is functional, functional needs repair, or nonfunctional — then use a categorical encoding that works for multi-class classification, such as [OrdinalEncoder](https://contrib.scikit-learn.org/categorical-encoding/ordinal.html) (not [TargetEncoder](https://contrib.scikit-learn.org/categorical-encoding/targetencoder.html))



## Stretch Goals

### Reading
- Jake VanderPlas, [Python Data Science Handbook, Chapter 5.3](https://jakevdp.github.io/PythonDataScienceHandbook/05.03-hyperparameters-and-model-validation.html), Hyperparameters and Model Validation
- Jake VanderPlas, [Statistics for Hackers](https://speakerdeck.com/jakevdp/statistics-for-hackers?slide=107)
- Ron Zacharski, [A Programmer's Guide to Data Mining, Chapter 5](http://guidetodatamining.com/chapter5/), 10-fold cross validation
- Sebastian Raschka, [A Basic Pipeline and Grid Search Setup](https://github.com/rasbt/python-machine-learning-book/blob/master/code/bonus/svm_iris_pipeline_and_gridsearch.ipynb)
- Peter Worcester, [A Comparison of Grid Search and Randomized Search Using Scikit Learn](https://blog.usejournal.com/a-comparison-of-grid-search-and-randomized-search-using-scikit-learn-29823179bc85)

### Doing
- Add your own stretch goals!
- Try other [categorical encodings](https://contrib.scikit-learn.org/categorical-encoding/). See the previous assignment notebook for details.
- In additon to `RandomizedSearchCV`, scikit-learn has [`GridSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html). Another library called scikit-optimize has [`BayesSearchCV`](https://scikit-optimize.github.io/notebooks/sklearn-gridsearchcv-replacement.html). Experiment with these alternatives.
- _[Introduction to Machine Learning with Python](http://shop.oreilly.com/product/0636920030515.do)_ discusses options for "Grid-Searching Which Model To Use" in Chapter 6:

> You can even go further in combining GridSearchCV and Pipeline: it is also possible to search over the actual steps being performed in the pipeline (say whether to use StandardScaler or MinMaxScaler). This leads to an even bigger search space and should be considered carefully. Trying all possible solutions is usually not a viable machine learning strategy. However, here is an example comparing a RandomForestClassifier and an SVC ...

The example is shown in [the accompanying notebook](https://github.com/amueller/introduction_to_ml_with_python/blob/master/06-algorithm-chains-and-pipelines.ipynb), code cells 35-37. Could you apply this concept to your own pipelines?

### BONUS: Stacking!

Here's some code you can use to "stack" multiple submissions, which is another form of ensembling:

```python
import pandas as pd

# Filenames of your submissions you want to ensemble
files = ['submission-01.csv', 'submission-02.csv', 'submission-03.csv']

target = 'status_group'
submissions = (pd.read_csv(file)[[target]] for file in files)
ensemble = pd.concat(submissions, axis='columns')
majority_vote = ensemble.mode(axis='columns')[0]

sample_submission = pd.read_csv('sample_submission.csv')
submission = sample_submission.copy()
submission[target] = majority_vote
submission.to_csv('my-ultimate-ensemble-submission.csv', index=False)
```

In [0]:
%%capture
import sys

# If you're on Colab:
if 'google.colab' in sys.modules:
    DATA_PATH = 'https://raw.githubusercontent.com/LambdaSchool/DS-Unit-2-Kaggle-Challenge/master/data/'
    !pip install category_encoders==2.*

# If you're working locally:
else:
    DATA_PATH = '../data/'

In [0]:
import pandas as pd

# Merge train_features.csv & train_labels.csv
train = pd.merge(pd.read_csv(DATA_PATH+'waterpumps/train_features.csv'), 
                 pd.read_csv(DATA_PATH+'waterpumps/train_labels.csv'))

# Read test_features.csv & sample_submission.csv
test = pd.read_csv(DATA_PATH+'waterpumps/test_features.csv')
sample_submission = pd.read_csv(DATA_PATH+'waterpumps/sample_submission.csv')

In [3]:
test.shape

(14358, 40)

In [4]:
import numpy as np
import category_encoders as ce

def wrangle(df):

  # Prevent error message
  X = df.copy()
  target='status_group'

  # Treat near-zero values like zero 
  X['latitude'] = X['latitude'].replace(-2e-08,0)

  # Replace zero values with nulls so we can impute later
  cols_with_zeros = ['longitude', 'latitude', 'construction_year', 
                       'gps_height', 'population']
  for col in cols_with_zeros:
      X[col] = X[col].replace(0, np.nan)
  
  # Drop super high unique value percentage values 
  X = X.drop(columns=['recorded_by','id'])

  # Convert date_recorded to datetime format so that we can calculate time between 
  # construction year and date recorded 
  X['date_recorded'] = pd.to_datetime(X['date_recorded'], infer_datetime_format=True)
  
  # Extract components from date_recorded, then drop the original column
  X['year_recorded'] = X['date_recorded'].dt.year

  # Engineer feature: how many years from construction_year to date_recorded
  X['years'] = X['year_recorded'] - X['construction_year']
  X['years_MISSING'] = X['years'].isnull()
  
  # Find amount of water per person
  X['water/person'] = X['amount_tsh'].replace({0:1}) / X['population'].replace({0:1})
  
  # Find average population served per year 
  X['pop/year'] = X['population'].replace({0:1}) / X['years'].replace({0:1})

  X = X.drop(columns=['date_recorded'])

  # Return wrangled dataframe
  return X

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [0]:
# Apply feature engineering to train data 
train = wrangle(train)
test = wrangle(test)

In [6]:
train.shape

(59400, 43)

In [7]:
test.shape

(14358, 42)

In [0]:
def encoder(df):
  target = 'status_group'
  if target in df.columns:
    df_features = df.drop(columns=[target])
  else:
    df_features = df
  numeric_features = df_features.select_dtypes(include='number')
  categorical = df_features.select_dtypes(exclude='number').nunique()
  cat_features = categorical[categorical <=50].index.tolist()
  high_cardinality_features = pd.DataFrame(categorical[categorical > 50])
  df_high = df[high_cardinality_features.T.columns]
  one_hot_encode = ce.OneHotEncoder(use_cat_names=True)
  one_hot_encode.fit(df[cat_features])
  low_cardinality_features = one_hot_encode.transform(df[cat_features])
  df1 = numeric_features.join(low_cardinality_features, how='outer')
  df2 = df1.join(df_high, how='outer')

  return df2

In [9]:
X_train = encoder(train)

X_train.head()

   amount_tsh  gps_height  ...        ward                  scheme_name
0      6000.0      1390.0  ...    Mundindi                        Roman
1         0.0      1399.0  ...       Natta                          NaN
2        25.0       686.0  ...     Ngorika  Nyumba ya mungu pipe scheme
3         0.0       263.0  ...    Nanyumbu                          NaN
4         0.0         NaN  ...  Nyakasimbi                          NaN

[5 rows x 199 columns]

In [10]:
X_train.shape

(59400, 199)

In [0]:
X_train = X_train.drop(['status_group_functional','status_group_non functional','status_group_functional needs repair'], axis=1)

In [12]:
X_test = encoder(test)

X_test.head()

   amount_tsh  gps_height  ...          ward     scheme_name
0         0.0      1996.0  ...        Bashay             NaN
1         0.0      1569.0  ...      Kimnyaki  TPRI pipe line
2         0.0      1567.0  ...          Puma               P
3         0.0       267.0  ...       Mkutano             NaN
4       500.0      1260.0  ...  Mbinga Urban          BRUDER

[5 rows x 194 columns]

In [13]:
set1 = set(X_train.columns)
set2 = set(X_test.columns)
set3 = set1.difference(set2)

print(set3)

{'extraction_type_other - mkulima/shinyanga', 'scheme_management_None'}

In [0]:
X_test['extraction_type_other - mkulima/shinyanga']=0

In [0]:
X_test['scheme_management_None'] = 0

In [16]:
X_test.shape

(14358, 196)

In [17]:
X_train.shape

(59400, 196)

In [0]:
# Import libraries and classes for pipelines

import category_encoders as ce
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [0]:
# Create target group and drop target from features columns

target = 'status_group'
features = train.columns.drop(target)

In [0]:
# Isolate train dataframes based on features and target groups 

X_train = train[features]
y_train = train[target]

In [0]:
# Make a pipeline for RandomForestRegressor cross-validation

pipeline = make_pipeline(
    ce.OrdinalEncoder(), 
    SimpleImputer(strategy='mean'), 
    RandomForestClassifier(random_state=42, n_jobs=-1)
)

In [0]:
param_distributions = {
    'randomforestclassifier__n_estimators': [100,110,120,130,140,150,200],
    'randomforestclassifier__min_samples_leaf': [2,5,7,9,10],
    'randomforestclassifier__random_state': [0,42]
}

search = RandomizedSearchCV (
    pipeline, 
    param_distributions=param_distributions,
    n_iter=5,
    cv=5,
    scoring='accuracy',
    verbose=10,
    return_train_score=True,
    n_jobs=-1
)

In [23]:
# Apply search to training data 

search.fit(X_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:   34.9s
[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-1)]: Done  14 tasks      | elapsed:  3.4min
[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed:  5.5min
[Parallel(n_jobs=-1)]: Done  25 out of  25 | elapsed:  6.4min remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  25 out of  25 | elapsed:  6.4min finished

RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=Pipeline(memory=None,
                                      steps=[('ordinalencoder',
                                              OrdinalEncoder(cols=None,
                                                             drop_invariant=False,
                                                             handle_missing='value',
                                                             handle_unknown='value',
                                                             mapping=None,
                                                             return_df=True,
                                                             verbose=0)),
                                             ('simpleimputer',
                                              SimpleImputer(add_indicator=False,
                                                            copy=True,
                                                            fill_value=None,
                                                            missing_values=nan,
                                                            strategy='mean',
                                                            verbose=0)...
                                      verbose=False),
                   iid='deprecated', n_iter=5, n_jobs=-1,
                   param_distributions={'randomforestclassifier__min_samples_leaf': [2,
                                                                                     5,
                                                                                     7,
                                                                                     9,
                                                                                     10],
                                        'randomforestclassifier__n_estimators': [100,
                                                                                 110,
                                                                                 120,
                                                                                 130,
                                                                                 140,
                                                                                 150,
                                                                                 200],
                                        'randomforestclassifier__random_state': [0,
                                                                                 42]},
                   pre_dispatch='2*n_jobs', random_state=None, refit=True,
                   return_train_score=True, scoring='accuracy', verbose=10)

In [0]:
# Check best parameters 

results = pd.DataFrame

In [25]:
# Check scores for different 5 fold values 

k = 7
scores = cross_val_score(pipeline, X_train, y_train, cv=k,
                         scoring='accuracy')

print(f'Accuracy for {k} folds is:', scores)

Accuracy for 7 folds is: [0.81074711 0.81263257 0.80980438 0.81204337 0.81015791 0.80447849
 0.80919269]

In [26]:
scores.mean()

0.8098652178577226

In [27]:
print('Model Hyperparameters:')
print(pipeline.named_steps['randomforestclassifier'])

Model Hyperparameters:
RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)